[package]
name = "tests"
version = "0.1.0"
edition = "2024"
publish = false

[features]
jwt = ["axum-security/jwt"]
cookie = ["axum-security/cookie"]
oauth2 = ["axum-security/oauth2"]
basic-auth = ["axum-security/basic-auth"]
rbac = ["axum-security/rbac", "axum-security/cookie"]
macros = ["rbac", "axum-security/macros"]
pbac = ["axum-security/pbac", "axum-security/cookie"]
oidc = ["axum-security/oidc"]
headers = ["axum-security/headers"]
jiff = ["axum-security/jiff"]
chrono = ["axum-security/chrono"]
time = ["axum-security/time"]


[dev-dependencies]
trybuild = { version = "1", features = ["diff"] }
axum-security = { path = "../axum-security", features = ["macros", "rbac", "cookie", "jwt"] }
axum = { workspace = true, features = ["query", "http1"] }
tower.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["macros", "time"] }
tracing.workspace = true
uuid.workspace = true
url = "2.5.8"
serde_urlencoded = "0.7"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
wiremock = "0.6.5"
reqwest = { version = "0.13.1", features = ["cookies"], default-features=false }
sha2 = "0.11"
base64 = "0.22"
openidconnect = { workspace = true }
chrono = "0.4"
jiff = { workspace = true }
time = { workspace = true }
serde_json = "1"
