[package]
name = "axum-security-oauth2"
version = "0.0.1"
edition = "2024"
authors = ["Joey de Waal <dewaaljoey@gmail.com>"]
license = "MIT"
description = "A minimal OAuth2 client library, part of the axum-security workspace"
repository = "https://github.com/joeydewaal/axum-security/"
documentation = "https://docs.rs/axum-security-oauth2"
keywords = ["security", "oauth2", "oauth", "http"]
categories = ["web-programming", "authentication", "asynchronous"]

[package.metadata.docs.rs]
all-features = true

[features]
default = ["reqwest", "rustls-tls"]
reqwest = ["dep:reqwest"]
rustls-tls = ["reqwest?/rustls-tls"]
native-tls = ["reqwest?/native-tls"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
base64.workspace = true
url.workspace = true
getrandom.workspace = true
subtle.workspace = true

reqwest = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
wiremock = "0.6"
