use std::fmt;

use base64::{Engine as _, engine::general_purpose::URL_SAFE_NO_PAD};
use subtle::ConstantTimeEq;

/// Compares two strings in constant time (for equal lengths; the length
/// itself is not hidden).
fn constant_time_eq(a: &str, b: &str) -> bool {
    a.as_bytes().ct_eq(b.as_bytes()).into()
}

/// Generates 32 bytes from the OS CSPRNG, base64url-nopad encoded.
pub(crate) fn random_b64() -> String {
    let mut bytes = [0u8; 32];
    getrandom::fill(&mut bytes).expect("failed to read from the OS random source");
    URL_SAFE_NO_PAD.encode(bytes)
}

macro_rules! secret_type {
    ($(#[$doc:meta])* $name:ident) => {
        $(#[$doc])*
        ///
        /// `Debug` prints `[redacted]`, there is no `Display` impl and
        /// comparisons run in constant time.
        #[derive(Clone)]
        pub struct $name(String);

        impl $name {
            /// Reconstructs the secret from a stored string (e.g. one that
            /// round-tripped through a cookie).
            pub fn new(secret: impl Into<String>) -> Self {
                Self(secret.into())
            }

            /// Returns the secret string.
            pub fn secret(&self) -> &str {
                &self.0
            }

            /// Consumes the wrapper and returns the secret string.
            pub fn into_secret(self) -> String {
                self.0
            }
        }

        impl fmt::Debug for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                f.write_str(concat!(stringify!($name), "([redacted])"))
            }
        }

        impl PartialEq for $name {
            fn eq(&self, other: &Self) -> bool {
                constant_time_eq(&self.0, &other.0)
            }
        }

        impl Eq for $name {}

        impl PartialEq<str> for $name {
            fn eq(&self, other: &str) -> bool {
                constant_time_eq(&self.0, other)
            }
        }

        impl PartialEq<&str> for $name {
            fn eq(&self, other: &&str) -> bool {
                constant_time_eq(&self.0, other)
            }
        }

        impl PartialEq<String> for $name {
            fn eq(&self, other: &String) -> bool {
                constant_time_eq(&self.0, other)
            }
        }
    };
}

secret_type! {
    /// An OAuth2 client secret.
    ClientSecret
}

secret_type! {
    /// An access token returned by the token endpoint.
    AccessToken
}

secret_type! {
    /// A refresh token returned by the token endpoint.
    RefreshToken
}

secret_type! {
    /// The authorization code sent by the authorization server to the
    /// redirect URL (the `code` query parameter).
    AuthorizationCode
}

secret_type! {
    /// The CSRF token sent as the `state` parameter on the authorization
    /// URL. Persist it when the login starts and compare it against the
    /// `state` query parameter on the callback.
    CsrfToken
}

secret_type! {
    /// A PKCE code verifier (RFC 7636). Generated by
    /// [`start_login`](crate::OAuth2Client::start_login), persisted by the
    /// caller and passed back to
    /// [`finish_login`](crate::OAuth2Client::finish_login).
    PkceVerifier
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn debug_is_redacted() {
        let secret = CsrfToken::new("super-secret-value");
        assert_eq!(format!("{secret:?}"), "CsrfToken([redacted])");
        assert!(!format!("{secret:?}").contains("super-secret-value"));
    }

    #[test]
    #[allow(clippy::cmp_owned)] // exercises `PartialEq<String>` on purpose
    fn eq_variants() {
        let token = CsrfToken::new("abc");
        assert_eq!(token, CsrfToken::new("abc"));
        assert_ne!(token, CsrfToken::new("abz"));
        assert_ne!(token, CsrfToken::new("abcd"));
        assert!(token == *"abc");
        assert!(token == "abc");
        assert!(token == String::from("abc"));

        // `&CsrfToken == &str` via std's blanket `PartialEq<&B> for &A`.
        let by_ref: &CsrfToken = &token;
        let state_param: &str = "abc";
        assert!(by_ref == state_param);
    }

    #[test]
    fn random_is_43_chars_url_safe() {
        let value = random_b64();
        assert_eq!(value.len(), 43); // 32 bytes, base64 no pad
        assert!(
            value
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
        );
        assert_ne!(random_b64(), random_b64());
    }

    #[test]
    fn round_trip() {
        let token = AccessToken::new("value");
        assert_eq!(token.secret(), "value");
        assert_eq!(token.into_secret(), "value");
    }
}
